dist: trusty
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  - "3.7"

os:
  - linux
  # - osx

sudo: required

osx_image: xcode9.4


install:
    - ./.travis/install.sh

# pypy is not passing, but allow failures for coverage stage to be reached
matrix:
  allow_failures:
    - python: pypy
    - os: osx

jobs:
  include:
    - &test_job
      stage: Test
      script: python tryit.py
      before_script: skip
      after_success: skip
      python: 2.7
    - <<: *test_job
      python: 3.7
      sudo: required
    - <<: *test_job
      python: 3.6
      sudo: required
    - <<: *test_job
      python: 3.5
      sudo: required
    - <<: *test_job
      python: 3.7-dev
      sudo: required

  