dist: xenial
language: python

# pypy is not passing, but allow failures for coverage stage to be reached
# matrix:
#   allow_failures:
#     - python: pypy
#     # - os: osx

jobs:
  include:
    - &test_job
      stage: Test
      script: python tryit.py
      before_script: skip
      after_success: skip
      python: 2.7
    - <<: *test_job
      python: 3.6
      sudo: required
    - <<: *test_job
      python: 3.5
      sudo: required
    - <<: *test_job
      python: 3.7
      sudo: required

install:
    - ./.travis/install.sh